version: '3.9'

services:

  boilerplate_service:
    image: boilerplate_service
    build: .
    container_name: boilerplate_service
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1440:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - myapp_network


networks:
  myapp_network:
    driver: bridge
volumes:
  mssql_data:
