[tool.ruff]

select = [
    "E",
    "F",
    "I",
    "C",
    "B",
    "M",
    "UP",
]
ignore = []

fixable = ["ALL"]
unfixable = []

exclude = [
    ".git",
    ".mypy_cache",
    ".pytype",
    ".ruff_cache",
    ".venv",
    "__pypackages__",
    "venv",
    "alembic/versions/",
]

line-length = 120

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

target-version = "py312"